### ISSUE TITLE
Incorrect C code generated when using present-when encoding and IA5Strings

### ISSUE THREAD

**Issue by michalkocon** [ttsiodras/asn1scc#112]
Using `present-when` encoding property inside `CHOICE` together with IA5String results in incorrect C code generation (asn.exe -c -ACN String.asn1 String.acn). Asn1scc inserts string without `""` so it's treated as undeclared variable. The second problem is as gcc says - `assignment to expression with array type`.

Example code causing these issues: [String.zip](https://github.com/ttsiodras/asn1scc/files/1407137/String.zip)

**Comment by gmamais** [comment]
Issue should be ok with the latest commit.
Btw, do not use names which conflict with C standard files (e.g. String.asn1). 
If you are OK, please close the ticket.
