### ISSUE TITLE
Automatic Test Cases header for C not wrapped by extern "C" for C++ compilers

### ISSUE THREAD

**Issue by dmarszk** [ttsiodras/asn1scc#116]
ATC generated in C need manual wrapping by extern "C" code to build and use them in C++.

**Comment by maxime-esa** [comment]
Why exactly? The test cases are self-contained and come with a makefile and a main function in C. Why would you need to build them in C++ ?

**Comment by dmarszk** [comment]
Honestly - I do not remember exactly!
I believe I intended to run the test suite within Arduino Studio, which, by default, forces its main translation unit to be a C++.
