### ISSUE TITLE
Does asn1scc support BER?

### ISSUE THREAD

**Issue by samrushing** [ttsiodras/asn1scc#12]
It's not clear: Program.cs has the command-line args for BER & XER commented out.
If I pass -BER to the compiler I get prototypes, but no implementation.

**Comment by maxime-esa** [comment]
XER is supported (use -XER together with either -c or -Ada) but not BER.

If you need these BER encoders and if you are familiar enough with ASN.1 you may find it quite easy to write the template files for these encoders. The tool uses the StringTemplate library (check the .stg files in the Backend.*.ST directories). The BER "runtime" is already there with all the basic functions for encoding/decoding all ASN.1 types (file ber.c). What is missing is the body of the functions that are specific to a particular grammar (to be defined in a ber.stg for C and Ada).

**Comment by samrushing** [comment]
I'm familiar enough with OCaml that I might be able to do this, but not in the near future (next month or two).  Thanks for the info!
