### ISSUE TITLE
Inconsistency in Ascii encoding between Ada and C

### ISSUE THREAD

**Issue by KonradKap** [ttsiodras/asn1scc#124]
ACN related parts:
`Positive[encoding ASCII, size 256]`

ASN.1 related parts:
```
Positive ::= INTEGER(1..MAX)
p Positive ::= 911
```

Encoding with Ada yields:
"`+0000000000000000000000000000911`"
whereas with C:
"`00000000000000000000000000000911`"

Then, when trying to decode the former in C, an assertion is thrown:
```
build/PositiveInt/Ascii/acn.c:683: Acn_Dec_UInt_ASCII_ConstSize:
Assertion `digit >= '0' && digit <= '9'' failed.']
```

The problem is caused by the '+' sign that Ada inserts.
Function `adaasn1rtl.Acn_Enc_Int_ASCII_ConstSize` puts the sign character at the very beginning of its body:
```
IF IntVal>=0 THEN
        tmp(1) := Character'Pos('+');
        intValCopy := IntVal;
    ELSE
        tmp(1) := Character'Pos('-');
        intValCopy := -IntVal;
END IF;
```
and, on C side, `Acn_Dec_UInt_ASCII_ConstSize` asserts against it.

This is one of the tests developed as a #117, tested with branch master.

**Comment by gmamais** [comment]
fixed in ASN1SCC_V4
