### ISSUE TITLE
[V4][XML.AST] <UPPERCASE> vs <CamelCase> for types related elements

### ISSUE THREAD

**Issue by hcorg** [ttsiodras/asn1scc#131]
Although I do see connection that (for example) ASN.1 `INTEGER` is now represented by `<INTEGER>` tag, it seems like inconsistency in XML itself - and I'm just fan of making things consistent ;) (even if it would mean - "change everything to UPPERCASE")

**Comment by hcorg** [comment]
also: `<Enumerated>` breaks convention

**Comment by gmamais** [comment]
Would you like to change <Enumerated> to <ENUMERATED> or code will break?

**Comment by hcorg** [comment]
change on our side will be quick, so change if you think it's a good idea :)

**Comment by gmamais** [comment]
Enumerated changed to ENUMERATED
