### ISSUE TITLE
[V4][XML.AST] Parametrized types "duplicate" type information

### ISSUE THREAD

**Issue by hcorg** [ttsiodras/asn1scc#133]
Subtree of parametrized type use copies tree from parametrized type definition, which makes multiple occurrences of same `Line` 'CharPositionsInLine` in file.

I know it's not something that could be fixed completely, but maybe at least some marker "this type comes from parametrized type"? So IDE could ignore subtree.

Final solution could include both - copied tree and additionally something like "ParentType" and "ParametrTypes" (or something named better :) )

**Comment by gmamais** [comment]
Added a new attribute ParameterizedTypeInstance="true" for those types

**Comment by hcorg** [comment]
thanks!
