### ISSUE TITLE
[V4] Crash when passing malformed constraint to IA5String or NumericString

### ISSUE THREAD

**Issue by psockoN7** [ttsiodras/asn1scc#149]
Given ASN.1:

```
MyModel DEFINITIONS ::= BEGIN

MyIA5String ::= IA5String("A" .. "Z")
MyNumericString ::= NumericString("1" .. "9")

END
```

when trying to generate code by calling `asn1.exe -c MyModel.asn`
uncaught ` Exception of type 'FsUtils+BugErrorException' ` is thrown. 

Even though presented code might be invalid ASN.1, the crash is unexpected.

**Comment by gmamais** [comment]
fixed
