### ISSUE TITLE
[V4] [AST XML] ENUMERATED Items should contain AdaName/CName

### ISSUE THREAD

**Issue by hcorg** [ttsiodras/asn1scc#161]
Currently only ASN.1 name is available, no information about results of applying renaming policy is available

**Comment by gmamais** [comment]
Do you mean the XML produced by -x ast.xml or using a custom backed?

**Comment by hcorg** [comment]
default, produced by `-x ast.xml`

if there is a chance to get that using custom backend we might consider switching to it

**Comment by gmamais** [comment]
The information is on the custom backends, but I will also add it to the default one.

**Comment by hcorg** [comment]
Thanks!

**Comment by gmamais** [comment]
CName and AdaName attributes were added in the ENUMERATED as well as in TypeAssignment and ValueAssignment tags (i.e. covers also issue 159).
If you are OK then please close these two issues.

**Comment by hcorg** [comment]
looks ok, thanks!
