### ISSUE TITLE
[AST XML] CName should be present even for anonymous inner types

### ISSUE THREAD

**Issue by hcorg** [ttsiodras/asn1scc#164]
Assume there is a inner CHOICE in a structure and I want to initialize one of its options. C code could look like this:

```
s.innerChoice.k = option2_PRESENT;
XXXXXX_Init(s.innerChoice.u.option2);
```

I need to know XXXXX to generate such code.

Or there should be some utility functions for easy switching selected union component and proper it's initialization (yeah, I know, C sucks...).

**Comment by maxime-esa** [comment]
It is there now. Given this grammar:

```
Foo DEFINITIONS ::=
BEGIN
 Seq ::= SEQUENCE {
   innerChoice CHOICE {
     option1 BOOLEAN,
     option2 INTEGER (0..233)
   }
 }
END
```

You can generate the C code and the AST like this:

```
asn1.exe -c -customStg ~/path/to/xml.stg:out.xml foo.asn
```

The XML contains the following:
```
<ChoiceChild VarName="option2" Line="6" CharPositionInLine="5" EnumID ="option2_PRESENT">
    <Type  cName="Seq_innerChoice_option2" adaName="Seq_innerChoice_option2">
```

So you have both **cName** and **option2_PRESENT**
