### ISSUE TITLE
[AST XML] Include ACN code location in XML

### ISSUE THREAD

**Issue by hcorg** [ttsiodras/asn1scc#165]
File, line number & column etc.

**Comment by gmamais** [comment]
a new (optional) tag was added under <Asn1Type> that containts the request information

<Asn1Type id="MyModel.MyEnum" Line="3" CharPositionInLine="11" ParameterizedTypeInstance="false">
       <AcnFileInfo File="a.acn" Line="3" CharPositionInLine="7" />
...

**Comment by usr3-1415** [comment]
Please close the ticket if the implementation covers your needs.
