### ISSUE TITLE
UPER size for "BIT STRING (SIZE (N))" is 8 times too large.

### ISSUE THREAD

**Issue by stevew1154** [ttsiodras/asn1scc#168]
Using ASN1SCC_V4 branch:

```
Foo ::= SEQUENCE {
   spare                          BIT STRING (SIZE (68))
}
```

Yields a reasonable structure Foo:
```
/*-- Foo --------------------------------------------*/
typedef struct {
    
    byte arr[9];
} Foo_spare;

typedef struct {
    Foo_spare spare;

} Foo;
```
And the decode/encode functions properly consume/produce 68 bits, but the sizing constants are off by a factor of 8:

```
#define Foo_REQUIRED_BYTES_FOR_ENCODING       68 
#define Foo_REQUIRED_BITS_FOR_ENCODING        544
```

**Comment by stevew1154** [comment]
My git commit is:

97dbd82 mantis 0000663 (almost completed)

**Comment by gmamais** [comment]
Thanks for reporting this bug.
The bug, which also affected the ICD generation, was fixed.
