### ISSUE TITLE
Installation instructions for fsharp compiler are incorrect

### ISSUE THREAD

**Issue by AlexanderFabisch** [ttsiodras/asn1scc#170]
The is no configure script:

```
git clone https://github.com/fsharp/fsharp && \
    cd fsharp && \
    ./configure && \
    make && sudo make install 
```

**Comment by ttsiodras** [comment]
Indeed, the instructions regarding F# are out of date now. Since the language now exists in pre-packaged form in all major distributions, I updated the README to remove this.

Closed with #cbf012ddf2ebbd220e2e611a94f93db19ad1e57c
