### ISSUE TITLE
code coverage tests fail for automatic generated test cases in corner cases of structure content

### ISSUE THREAD

**Issue by joluxer** [ttsiodras/asn1scc#204]
The same ASN.1/ACN grammar which fails with renaming (issue #202 ) also fails for the `-atc` generated test cases in some corner cases.

**Comment by usr3-1415** [comment]
I could not reproduce the error. The generated code compiles successfully and all test cases pass.
Here is the output
$ make coverage
make && ./mainprogram && \
    gcov adyytsdy-upvw-dcdpwvyxtx.c adyytsdy-upvw-odpgdp.c mjy-onyxdw-ndukekxkvey.c mxo-xvwwhekjtxkve.c
make[1]: Entering directory '/cygdrive/c/prj/GitHub/asn1scc/tmp/006/out3'
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o Adyytsdy-upvw-Dcdpwvyxtx.o Adyytsdy-upvw-Dcdpwvyxtx.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o Adyytsdy-upvw-Dcdpwvyxtx_auto_tcs.o Adyytsdy-upvw-Dcdpwvyxtx_auto_tcs.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o Adyytsdy-upvw-Odpgdp.o Adyytsdy-upvw-Odpgdp.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o Adyytsdy-upvw-Odpgdp_auto_tcs.o Adyytsdy-upvw-Odpgdp_auto_tcs.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o asn1crt.o asn1crt.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o asn1crt_encoding.o asn1crt_encoding.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o asn1crt_encoding_acn.o asn1crt_encoding_acn.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o asn1crt_encoding_uper.o asn1crt_encoding_uper.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o mainprogram.o mainprogram.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o Mjy-Onyxdw-Ndukekxkvey.o Mjy-Onyxdw-Ndukekxkvey.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o Mjy-Onyxdw-Ndukekxkvey_auto_tcs.o Mjy-Onyxdw-Ndukekxkvey_auto_tcs.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o MXO-Xvwwhekjtxkve.o MXO-Xvwwhekjtxkve.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o MXO-Xvwwhekjtxkve_auto_tcs.o MXO-Xvwwhekjtxkve_auto_tcs.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o test_case_001.o test_case_001.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o test_case_002.o test_case_002.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o test_case_003.o test_case_003.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o test_case_004.o test_case_004.c
gcc -c -g -Wall -Werror -Wextra -Wuninitialized -Wcast-qual -Wshadow -Wundef -fdiagnostics-show-option -D_DEBUG -DWORD_SIZE=4 -DFP_WORD_SIZE=4 -I . -O0 -fprofile-arcs -ftest-coverage -o testsuite.o testsuite.c
gcc -g -o mainprogram Adyytsdy-upvw-Dcdpwvyxtx.o Adyytsdy-upvw-Dcdpwvyxtx_auto_tcs.o Adyytsdy-upvw-Odpgdp.o Adyytsdy-upvw-Odpgdp_auto_tcs.o asn1crt.o asn1crt_encoding.o asn1crt_encoding_acn.o asn1crt_encoding_uper.o mainprogram.o Mjy-Onyxdw-Ndukekxkvey.o Mjy-Onyxdw-Ndukekxkvey_auto_tcs.o MXO-Xvwwhekjtxkve.o MXO-Xvwwhekjtxkve_auto_tcs.o test_case_001.o test_case_002.o test_case_003.o test_case_004.o testsuite.o -g -ftest-coverage -fprofile-arcs
make[1]: Leaving directory '/cygdrive/c/prj/GitHub/asn1scc/tmp/006/out3'
All test cases (334) run successfully.
adyytsdy-upvw-dcdpwvyxtx.gcno:version 'A93*', prefer 'A83f'
adyytsdy-upvw-dcdpwvyxtx.gcno:no functions found
adyytsdy-upvw-dcdpwvyxtx.gcda:version 'A93*', prefer version 'A83f'
adyytsdy-upvw-odpgdp.gcno:version 'A93*', prefer 'A83f'
adyytsdy-upvw-odpgdp.gcda:version 'A93*', prefer version 'A83f'
mjy-onyxdw-ndukekxkvey.gcno:version 'A93*', prefer 'A83f'
mjy-onyxdw-ndukekxkvey.gcda:version 'A93*', prefer version 'A83f'
mxo-xvwwhekjtxkve.gcno:version 'A93*', prefer 'A83f'
mxo-xvwwhekjtxkve.gcda:version 'A93*', prefer version 'A83f'
File 'Adyytsdy-upvw-Odpgdp.c'
Lines executed:76.46% of 1317
Creating 'Adyytsdy-upvw-Odpgdp.c.gcov'

File 'Mjy-Onyxdw-Ndukekxkvey.c'
Lines executed:94.04% of 369
Creating 'Mjy-Onyxdw-Ndukekxkvey.c.gcov'

File 'MXO-Xvwwhekjtxkve.c'
Lines executed:47.38% of 2294
Creating 'MXO-Xvwwhekjtxkve.c.gcov'
