### ISSUE TITLE
Default setting for optional value is set to true

### ISSUE THREAD

**Issue by giso-c** [ttsiodras/asn1scc#206]
When we add a variable as OPTIONAL in an asn structure and generate c code, the initialisation function of the struct will set the optional value as existing "pVal->exist.temperature = 1;"
Is it defines in the standard or it is a command parameter to define the default state of optional data.
Would be much more convenient when initialising a structure,  to set it to 0. The application would then change it when the optional data is inserted in the struct.

**Comment by maxime-esa** [comment]
I could agree, but the problem is that changing this behavior could have an impact on existing software, so I propose to leave it as is.
