### ISSUE TITLE
Self-contradicting WITH COMPONENTS specification for a SEQUENCE does not produce an error.

### ISSUE THREAD

**Issue by Lurkerpas** [ttsiodras/asn1scc#215]
Let's consider the following code:

```
RecordWithAnOptionalField ::= SEQUENCE {
    requiredItem DataUnit,
    optionalItem1 AlternativeDataUnit OPTIONAL,
    optionalItem2 AlternativeDataUnit OPTIONAL
}

DerivedRecord ::= RecordWithAnOptionalField (WITH COMPONENTS {optionalItem1 ABSENT, optionalItem1 PRESENT})
```

optionalItem1 is marked as both ABSENT and PRESENT (this construct was created by a mistake, due to a typo). When generating an ICD, no error is generated (it should), and the following ICD is produced:
![image](https://user-images.githubusercontent.com/17752977/113292596-05fc5d80-92f5-11eb-9014-273089d86b12.png)

**Comment by usr3-1415** [comment]
Fixed. asn1scc now reports an error.
A new test case was also added to cover this case.
