### ISSUE TITLE
Feature-request - payload size definitions

### ISSUE THREAD

**Issue by pakar** [ttsiodras/asn1scc#254]
A useful feature, IMO, in this tool would be to generate defines for the largest possible size a payload may be. With this i'm referring to the maximum size a payload may requires if all optional fields are included.

In my case the generated code is C and i'm working with a device with 32kb of ram and 256kb of flash (XiP) using UPER as output/input format. Each new/updated payload in the spec currently requires manual work to recalculate needed buffersizes where that payload is used and that is timeconsuming and error-prone.

This feature would allow easy declaration of buffers on the stack and reduce the manual work for memory optimizations.

Dynamic payloads would still require some manual work, but as each optional section would have a define for it's size you would just deduct the size of the excluded sections.

IMO Defines makes the most sense to use for this feature as it's main target would be embedded devices without dynamic memory allocation and where buffers are placed on the stack. It also makes it possible to use automated tools to analyze max stack-usage build-time.

**Comment by maxime-esa** [comment]
Unless I misunderstand your request, this is already supported. 
For every type, two defines are generated for the exact purpose of static buffer allocation:
For example:

![image](https://user-images.githubusercontent.com/1416005/207035018-0d0f251c-089c-4f2c-8c3a-85f5d26af2e9.png)
