### ISSUE TITLE
Problem running ./asn1-docker.sh

### ISSUE THREAD

**Issue by Sedictious** [ttsiodras/asn1scc#261]
I had a problem when running `./asn1-docker.sh`. No matter what arguments I tried to passed it prompted me to insert a filename (`ERROR: missing parameter '<files>...'.`) and just dumped its manpage

After changing the script from `[...] asn1scc-runtime /opt/asn1scc/asn1scc "$@"` to `[...] asn1scc-runtime "$@"` everything started working as expected

**Comment by usr3-1415** [comment]
Fixed!
Thanks for reporting the issue.
