### ISSUE TITLE
Recursive _IsConstraintValid()

### ISSUE THREAD

**Issue by escmmo** [ttsiodras/asn1scc#263]
asn1scc version 4.5.0.4
The compiler produces an _IsContraintValid() function that calls itself unconditionally:

```
flag T_STRUCT_member_IsConstraintValid(const T_STRUCT_member* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = T_STRUCT_member_IsConstraintValid(pVal, pErrCode);
    if (ret) {
        ret = ((*(pVal)) == 100UL);
        *pErrCode = ret ? 0 :  ERR_T_STRUCT_MEMBER_2_2; 
    }   /*COVERAGE_IGNORE*/

        return ret;
}
```

The .asn definition that generates this is:

```
T-uint32 ::= INTEGER(0..4294967295)

T-SOME-TYPE ::= T-uint32

T-STRUCT ::= SEQUENCE
{
	member	T-SOME-TYPE (100)
}
```

The key points which trigger this behavior are:
- defining one type on top of another type (`T-SOME-TYPE` on top of `T-uint32`)
- having the SEQUENCE `member` of that type with a specified value (100).

If `member` is defined as `T-uint32` instead, or no value is specified, no recursive function is created.

**Comment by maxime-esa** [comment]
Reproduced. We are looking into it, thanks for reporting.

**Comment by usr3-1415** [comment]
Issue Fixed.
Thanks for reporting the issue.
