### ISSUE TITLE
Custom types

### ISSUE THREAD

**Issue by iulianpana** [ttsiodras/asn1scc#64]
Hello,

Is it possible to have custom types specified in an ASN1 grammar, equivalent to basic C types?
E.g. for unsigned short type can i specify an ASN1 grammar in order to generate an unsigned short equivalent? I have tried using an INTEGER(0..65535) constraint, but it generates an uint64_t and verifies its constraints, but still an integer with 32 or 64 bits in length, according to target architecture.

I have manually modified the generated code in order to obtain the desired requirements.

I also attach a small project in order to show the patch i used. It contains:
 i)**asn1-sources folder**: the asn1 sources of the type equivalent to the C standard unsigned short type (mytype.asn1 file) and the definition of a message structure that has fields defined using the previous mentioned type (includingtype.asn1 file);

ii)**generated-c-sources**: the C files generated by the asn1 compiler.

iii)**modified-c-sources**: C files generated by the asn1 compiler and modified in order to accommodate the internal requirements to the unsigned short type.

Could you, please, tell me if  there is an workaround to manual modifications?
And is this okay 

from your point of view ?

Best regards,
Iulian.

[base-types-mockup.tar.gz](https://github.com/ttsiodras/asn1scc/files/368824/base-types-mockup.tar.gz)

**Comment by ttsiodras** [comment]
Hi Iulian.

Unfortunately it's not as easy as it seems. The run-time library (RTL) code has been implemented using this as a basis - that integers are mapped in a "large enough" form for pretty much all actions. If we had chosen to be more optimal in mapping INTEGER declarations to the "smallest C integer type that can accommodate them", then the interaction between RTL functions would be more complex - especially in light of code that is safety critical and must pass through compilations and static analysis tools without any warnings (encoding functions like those in asn1crt.c would have to be declared for each target "zone" - and the proper ones selected during code generation, etc).  This is all the more important for SPARK/Ada outputs, where the interaction between different "bit-width" values would make things even more complex.

In the end, as with all things, this is a balancing act - the decision to use a common representation makes things much simpler to reason about. And for most uses of ASN1SCC, what matters is what is the result of encoding (that ends up transmitted across communication lines) - where indeed, ranges are taken very much into account: an INTEGER(0..15) will only need 4 bits "on the wire" in UPER encodings, etc.
