### ISSUE TITLE
supports X400 P1 definition?

### ISSUE THREAD

**Issue by davidmoten** [ttsiodras/asn1scc#65]
Hi
Very cool project. Just wondering if the code generator would have any hiccups with a big fully blown ASN.1 definition like X400's P1? Are there features of ASN.1 that asn1scc does not support?

**Comment by ttsiodras** [comment]
Hi David.

ASN1SCC is geared towards safety-critical environments, so yes; there are ASN.1 features that we don't support. Anything that you can relate to a need for dynamic memory allocations, for example, is out of our scope - we only support ASN.1 grammars with e.g. fixed upper bounds in SEQUENCE OFs. We don't support ASN.1 extensions (the "three dots" construct) - etc.

The size of the grammar is not an issue - we can handle arbitrarily complex grammars, as long as they use constructs we allow. 

And prioritization-wise, we obviously target safety-critical functionality first - e.g. our SPARK/Ada output provides guarantees that very few (if any!) compilers offer... our automatically generated test cases provide 100% coverage of your grammar's encoders/decoders by construction, etc.

I am not aware of X400 specifically, but it's very easy to simply try feeding your ASN.1 grammar to ASN1SCC and see what happens.

Good luck!
