### ISSUE TITLE
 GetStrmPos(ByteStream*) is redundant  - should be removed

### ISSUE THREAD

**Issue by vgheo** [ttsiodras/asn1scc#68]
e6e6cc79decce700c20811c97261db6971d3336a

int GetStrmPos(ByteStream\* pByteStrm) {
    return pByteStrm->currentByte;
}
asn1SccSint ByteStream_GetLength(ByteStream\* pStrm)
{
    return pStrm->currentByte;
}

GetStrmPos is not used from the runtime.  Maybe generated code uses it ?

Also, it does not have appropriate prefix while it is an external function.

**Comment by ttsiodras** [comment]
Trying it out - created a new branch removing this function, will merge it in if regression passes.

**Comment by maxime-esa** [comment]
In V4 branch the function is still there in ber.c. Can we remove it and close this issue ?

**Comment by gmamais** [comment]
fixed in ASN1SCC_V4
