### ISSUE TITLE
Why is "Replace" in PascalCase?

### ISSUE THREAD

**Issue by RBM-GITHUB** [ttsiodras/asn1scc#75]
https://github.com/ttsiodras/asn1scc/blob/master/Ast/FsUtils.fs#L229

I'm new to GitHub and F#. I was reading some code and then I wondered why this modular function "Replace" was capitalized?

**Comment by ttsiodras** [comment]
Hi.

You can capitalize your functions any way you want in F# - try renaming the one in question (see http://pastebin.com/uFGcV7cv ) and you will see that everything still works fine.
